name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  build:
    name: Build (${{ matrix.os }}/${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            os: Linux
            arch: X64
          - runner: macos-13
            os: macOS
            arch: X64
          - runner: macos-14
            os: macOS
            arch: ARM64
    steps:
      - env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
        run: |
          if [[ "$OS" != "$RUNNER_OS" || "$ARCH" != "$RUNNER_ARCH" ]]; then
            echo "::error title=Unexpected Runner::Expected $OS/$ARCH, got $RUNNER_OS/$RUNNER_ARCH"
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Build
        run: go build -o glif .

      - name: Test
        run: go test -v ./...

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: glif-${{ matrix.os }}-${{ matrix.arch }}
          path: glif